### ISSUE TITLE
Direct link to Thing Description ontology .ttl file return 404

### ISSUE THREAD

**Issue by relu91** [w3c/wot-resources#22]
If you try to access the ontology `.ttl` from https://www.w3.org/2019/wot/td# using the link at the top of the page you get an [error page](https://www.w3.org/2019/wot/td.ttl). If you access it with the right header it works, but we should give the ability to link the file directly without any special header.

**Comment by egekorkan** [comment]
I have noticed further issues:
- For https://www.w3.org/2019/wot/security.ttl we get a multiple options page. Same for [hypermedia](https://www.w3.org/2019/wot/hypermedia.ttl) and [jsonschema](https://www.w3.org/2019/wot/json-schema.ttl)
- TM.ttl has the same issue: https://www.w3.org/2022/wot/tm.ttl gives 404
- We are not versioning the .htaccess files even though they are public at https://www.w3.org/2019/wot/.htaccess and https://www.w3.org/2022/wot/.htaccess

**Comment by egekorkan** [comment]
We discussed in the TD coordination call:
- We should not mislead the reader that there is an HTML link to a TTL file, which is currently happening.
- We need some text to explain how a reader should use these files. This means that the current file they are looking at is the rendered version in HTML. For TTL, they should either go to GitHub or preferably use content negotiation with another HTTP client to get the TTL version.
- We can put the link to GitHub resources at https://raw.githubusercontent.com/w3c/wot-resources/main/td/v1.1/ontology/hctl.ttl
- We can put a type attribute to the link (see https://www.w3schools.com/tags/att_a_type.asp). Doing some tests in the debug window did not work. We need some understanding why.
